/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerAttributeOption
 */
export interface EntitymanagerAttributeOption {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EntitymanagerAttributeOption
     */
    'option'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof EntitymanagerAttributeOption
     */
    'sort'?: number;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerAttributeOption
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerAttributeOption
     */
    'code'?: string;
    /**
     * 
     * @type {ProductentitymanagerLocalizedText}
     * @memberof EntitymanagerAttributeOption
     */
    'value'?: ProductentitymanagerLocalizedText;
    /**
     * 
     * @type {Array<EntitymanagerAttributeOptionSwatch>}
     * @memberof EntitymanagerAttributeOption
     */
    'swatches'?: Array<EntitymanagerAttributeOptionSwatch>;
}
