/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerUpdateAttributeGroupRequest
 */
export interface EntitymanagerUpdateAttributeGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeGroupRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeGroupRequest
     */
    'code'?: string;
    /**
     * 
     * @type {EntitymanagerUpdateAttributeGroupRequestPayload}
     * @memberof EntitymanagerUpdateAttributeGroupRequest
     */
    'payload'?: EntitymanagerUpdateAttributeGroupRequestPayload;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeGroupRequest
     */
    'fieldMask'?: string;
}
