/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EntitymanagerTypes = {
    Text: 'TEXT',
    Number: 'NUMBER',
    Boolean: 'BOOLEAN',
    Datetime: 'DATETIME',
    External: 'EXTERNAL',
    Embed: 'EMBED',
    Float32: 'FLOAT32'
} as const;
export type EntitymanagerTypes = typeof EntitymanagerTypes[keyof typeof EntitymanagerTypes];


export function EntitymanagerTypesFromJSON(json: any): EntitymanagerTypes {
    return EntitymanagerTypesFromJSONTyped(json, false);
}

export function EntitymanagerTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitymanagerTypes {
    return json as EntitymanagerTypes;
}

export function EntitymanagerTypesToJSON(value?: EntitymanagerTypes | null): any {
    return value as any;
}

