/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerEntity
 */
export interface EntitymanagerEntity {
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerEntity
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerEntity
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerEntity
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerEntity
     */
    'parentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerEntity
     */
    'label'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntitymanagerEntity
     */
    'relationships'?: Array<string>;
    /**
     * 
     * @type {Array<EntitymanagerAttribute>}
     * @memberof EntitymanagerEntity
     */
    'attributes'?: Array<EntitymanagerAttribute>;
}
