/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerListEntitiesResponse
 */
export interface EntitymanagerListEntitiesResponse {
    /**
     * 
     * @type {Array<EntitymanagerEntity>}
     * @memberof EntitymanagerListEntitiesResponse
     */
    'entities'?: Array<EntitymanagerEntity>;
    /**
     * 
     * @type {number}
     * @memberof EntitymanagerListEntitiesResponse
     */
    'nextPage'?: number;
}
