/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerUpdateAttributeRequestPayload
 */
export interface EntitymanagerUpdateAttributeRequestPayload {
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeRequestPayload
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeRequestPayload
     */
    'default'?: string;
    /**
     * 
     * @type {number}
     * @memberof EntitymanagerUpdateAttributeRequestPayload
     */
    'sort'?: number;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeRequestPayload
     */
    'groupCode'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EntitymanagerUpdateAttributeRequestPayload
     */
    'title'?: { [key: string]: string; };
    /**
     * 
     * @type {EntitymanagerRenderAs}
     * @memberof EntitymanagerUpdateAttributeRequestPayload
     */
    'renderAs'?: EntitymanagerRenderAs;
}
