/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerAttributeWriteError
 */
export interface EntitymanagerAttributeWriteError {
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerAttributeWriteError
     */
    'errorCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerAttributeWriteError
     */
    'attributeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerAttributeWriteError
     */
    'message'?: string;
}
