/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerOptionsList
 */
export interface EntitymanagerOptionsList {
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerOptionsList
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerOptionsList
     */
    'name'?: string;
}
