/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerCreateAttributeGroupRequest
 */
export interface EntitymanagerCreateAttributeGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerCreateAttributeGroupRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerCreateAttributeGroupRequest
     */
    'code'?: string;
    /**
     * 
     * @type {ProductentitymanagerLocalizedText}
     * @memberof EntitymanagerCreateAttributeGroupRequest
     */
    'label'?: ProductentitymanagerLocalizedText;
    /**
     * 
     * @type {number}
     * @memberof EntitymanagerCreateAttributeGroupRequest
     */
    'sort'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntitymanagerCreateAttributeGroupRequest
     */
    'visibility'?: Array<string>;
}
