/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EntitymanagerRenderAs = {
    Default: 'DEFAULT',
    Wysiwyg: 'WYSIWYG'
} as const;
export type EntitymanagerRenderAs = typeof EntitymanagerRenderAs[keyof typeof EntitymanagerRenderAs];


export function EntitymanagerRenderAsFromJSON(json: any): EntitymanagerRenderAs {
    return EntitymanagerRenderAsFromJSONTyped(json, false);
}

export function EntitymanagerRenderAsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitymanagerRenderAs {
    return json as EntitymanagerRenderAs;
}

export function EntitymanagerRenderAsToJSON(value?: EntitymanagerRenderAs | null): any {
    return value as any;
}

