/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EntitymanagerUpdateAttributeRequest
 */
export interface EntitymanagerUpdateAttributeRequest {
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeRequest
     */
    'code'?: string;
    /**
     * 
     * @type {EntitymanagerEntityIdentifier}
     * @memberof EntitymanagerUpdateAttributeRequest
     */
    'entityData'?: EntitymanagerEntityIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeRequest
     */
    'entityId'?: string;
    /**
     * 
     * @type {EntitymanagerUpdateAttributeRequestPayload}
     * @memberof EntitymanagerUpdateAttributeRequest
     */
    'payload'?: EntitymanagerUpdateAttributeRequestPayload;
    /**
     * 
     * @type {string}
     * @memberof EntitymanagerUpdateAttributeRequest
     */
    'fieldMask'?: string;
}
