/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListProductsRequestFilter
 */
export interface ListProductsRequestFilter {
    /**
     * 
     * @type {Date}
     * @memberof ListProductsRequestFilter
     */
    'createdAtStart'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListProductsRequestFilter
     */
    'createdAtEnd'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListProductsRequestFilter
     */
    'updatedAtStart'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListProductsRequestFilter
     */
    'updatedAtEnd'?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof ListProductsRequestFilter
     */
    'status'?: boolean;
}
