/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductAssetData
 */
export interface ProductAssetData {
    /**
     * 
     * @type {string}
     * @memberof ProductAssetData
     */
    'assetGrn'?: string;
    /**
     * 
     * @type {ProductLocalizedAsset}
     * @memberof ProductAssetData
     */
    'localizedAssetGrn'?: ProductLocalizedAsset;
    /**
     * 
     * @type {number}
     * @memberof ProductAssetData
     */
    'position'?: number;
    /**
     * 
     * @type {Array<ProductAssetsEntryMetadata>}
     * @memberof ProductAssetData
     */
    'metadata'?: Array<ProductAssetsEntryMetadata>;
}
