/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductBulkUpdateAssetsEntriesRequest
 */
export interface ProductBulkUpdateAssetsEntriesRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductBulkUpdateAssetsEntriesRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductBulkUpdateAssetsEntriesRequest
     */
    'productId'?: string;
    /**
     * 
     * @type {Array<BulkUpdateAssetsEntriesRequestUpdateEntity>}
     * @memberof ProductBulkUpdateAssetsEntriesRequest
     */
    'assets'?: Array<BulkUpdateAssetsEntriesRequestUpdateEntity>;
}
