/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductProductVariant
 */
export interface ProductProductVariant {
    /**
     * 
     * @type {string}
     * @memberof ProductProductVariant
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductProductVariant
     */
    'grn'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductProductVariant
     */
    'maxSaleableQuantity'?: number;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof ProductProductVariant
     */
    'attributes'?: { [key: string]: ProtobufAny; };
}
