/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductCreateProductResponse
 */
export interface ProductCreateProductResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreateProductResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateProductResponse
     */
    'id'?: string;
    /**
     * 
     * @type {Array<ProductProductResponseError>}
     * @memberof ProductCreateProductResponse
     */
    'productErrors'?: Array<ProductProductResponseError>;
    /**
     * 
     * @type {Array<ProductAttributeResponseError>}
     * @memberof ProductCreateProductResponse
     */
    'attributeErrors'?: Array<ProductAttributeResponseError>;
}
