/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductListProductsResponse
 */
export interface ProductListProductsResponse {
    /**
     * 
     * @type {Array<ProductProductEntity>}
     * @memberof ProductListProductsResponse
     */
    'products'?: Array<ProductProductEntity>;
    /**
     * 
     * @type {string}
     * @memberof ProductListProductsResponse
     */
    'nextPageToken'?: string;
}
