/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductGetProductByCodeResponse
 */
export interface ProductGetProductByCodeResponse {
    /**
     * 
     * @type {ProductProductEntity}
     * @memberof ProductGetProductByCodeResponse
     */
    'product'?: ProductProductEntity;
}
