/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductListProductsRequest
 */
export interface ProductListProductsRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductListProductsRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductListProductsRequest
     */
    'pageSize'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductListProductsRequest
     */
    'pageToken'?: string;
    /**
     * 
     * @type {ListProductsRequestFilter}
     * @memberof ProductListProductsRequest
     */
    'filter'?: ListProductsRequestFilter;
    /**
     * 
     * @type {string}
     * @memberof ProductListProductsRequest
     */
    'filterMask'?: string;
}
