/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductBulkUpdateResponseV2Response
 */
export interface ProductBulkUpdateResponseV2Response {
    /**
     * 
     * @type {string}
     * @memberof ProductBulkUpdateResponseV2Response
     */
    'productId'?: string;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof ProductBulkUpdateResponseV2Response
     */
    'attributes'?: { [key: string]: ProtobufAny; };
}
