/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductBulkUpdateRequestV2
 */
export interface ProductBulkUpdateRequestV2 {
    /**
     * 
     * @type {string}
     * @memberof ProductBulkUpdateRequestV2
     */
    'tenantId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductBulkUpdateRequestV2
     */
    'productIds'?: Array<string>;
    /**
     * 
     * @type {ProductBulkUpdateRequestV2Payload}
     * @memberof ProductBulkUpdateRequestV2
     */
    'payload'?: ProductBulkUpdateRequestV2Payload;
}
