/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductAddMediaGalleryEntryRequest
 */
export interface ProductAddMediaGalleryEntryRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductAddMediaGalleryEntryRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductAddMediaGalleryEntryRequest
     */
    'productId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductAddMediaGalleryEntryRequest
     */
    'assetGrn'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductAddMediaGalleryEntryRequest
     */
    'position'?: number;
    /**
     * 
     * @type {Array<ProductMediaGalleryEntryMetadata>}
     * @memberof ProductAddMediaGalleryEntryRequest
     */
    'metadata'?: Array<ProductMediaGalleryEntryMetadata>;
}
