/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductCreateProductRequest
 */
export interface ProductCreateProductRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductCreateProductRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateProductRequest
     */
    'entityType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateProductRequest
     */
    'entityCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateProductRequest
     */
    'code'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreateProductRequest
     */
    'isConfigurable'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductCreateProductRequest
     */
    'variantAttributes'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreateProductRequest
     */
    'isVirtual'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreateProductRequest
     */
    'isGiftcard'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreateProductRequest
     */
    'hasConfigurator'?: boolean;
    /**
     * 
     * @type {ProductLocalizedText}
     * @memberof ProductCreateProductRequest
     */
    'urlKey'?: ProductLocalizedText;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateProductRequest
     */
    'maxSaleableQuantity'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductCreateProductRequest
     */
    'mediaVariantAttributes'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof ProductCreateProductRequest
     */
    'attributes'?: { [key: string]: ProtobufAny; };
    /**
     * 
     * @type {{ [key: string]: ProductProductVariant; }}
     * @memberof ProductCreateProductRequest
     */
    'variants'?: { [key: string]: ProductProductVariant; };
}
