/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductListProductsByIdsRequest
 */
export interface ProductListProductsByIdsRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductListProductsByIdsRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductListProductsByIdsRequest
     */
    'ids'?: Array<string>;
}
