/* tslint:disable */
/* eslint-disable */
/**
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductUpdateProductRequestV2
 */
export interface ProductUpdateProductRequestV2 {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateProductRequestV2
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateProductRequestV2
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateProductRequestV2
     */
    'code'?: string;
    /**
     * 
     * @type {ProductFieldMask}
     * @memberof ProductUpdateProductRequestV2
     */
    'attributesMask'?: ProductFieldMask;
    /**
     * 
     * @type {ProductLocalizedText}
     * @memberof ProductUpdateProductRequestV2
     */
    'urlKey'?: ProductLocalizedText;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdateProductRequestV2
     */
    'maxSaleableQuantity'?: number;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof ProductUpdateProductRequestV2
     */
    'attributes'?: { [key: string]: ProtobufAny; };
    /**
     * 
     * @type {{ [key: string]: ProductProductVariant; }}
     * @memberof ProductUpdateProductRequestV2
     */
    'variants'?: { [key: string]: ProductProductVariant; };
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductUpdateProductRequestV2
     */
    'mediaVariantAttributes'?: Array<string>;
}
