/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductUpdateAssetEntryPayload } from '../models/ProductUpdateAssetEntryPayload';
import { HttpFile } from '../http/http';

export class BulkUpdateAssetsEntriesRequestUpdateEntity {
    'id'?: string;
    'payload'?: ProductUpdateAssetEntryPayload;
    'payloadMask'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "ProductUpdateAssetEntryPayload",
            "format": ""
        },
        {
            "name": "payloadMask",
            "baseName": "payloadMask",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkUpdateAssetsEntriesRequestUpdateEntity.attributeTypeMap;
    }

    public constructor() {
    }
}

