/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EntitymanagerAttributeOptionSwatch {
    'grn'?: string;
    'hex'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "hex",
            "baseName": "hex",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerAttributeOptionSwatch.attributeTypeMap;
    }

    public constructor() {
    }
}

