/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerGetAttributeOptionsRequestOption } from '../models/EntitymanagerGetAttributeOptionsRequestOption';
import { HttpFile } from '../http/http';

export class EntitymanagerGetAttributeOptionsRequest {
    'tenantId'?: string;
    'optionIds'?: Array<EntitymanagerGetAttributeOptionsRequestOption>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "optionIds",
            "baseName": "optionIds",
            "type": "Array<EntitymanagerGetAttributeOptionsRequestOption>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerGetAttributeOptionsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

