/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerAttribute } from '../models/EntitymanagerAttribute';
import { EntitymanagerEntityIdentifier } from '../models/EntitymanagerEntityIdentifier';
import { HttpFile } from '../http/http';

export class EntitymanagerBulkCreateAttributeRequest {
    'tenantId'?: string;
    'entityData'?: EntitymanagerEntityIdentifier;
    'entityId'?: string;
    'attributes'?: Array<EntitymanagerAttribute>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityData",
            "baseName": "entityData",
            "type": "EntitymanagerEntityIdentifier",
            "format": ""
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<EntitymanagerAttribute>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerBulkCreateAttributeRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

