/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerAttributeOptionSwatch } from '../models/EntitymanagerAttributeOptionSwatch';
import { ProductentitymanagerLocalizedText } from '../models/ProductentitymanagerLocalizedText';
import { HttpFile } from '../http/http';

export class EntitymanagerAttributeOption {
    'option'?: { [key: string]: string; };
    'sort'?: number;
    'id'?: string;
    'code'?: string;
    'value'?: ProductentitymanagerLocalizedText;
    'swatches'?: Array<EntitymanagerAttributeOptionSwatch>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "option",
            "baseName": "option",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ProductentitymanagerLocalizedText",
            "format": ""
        },
        {
            "name": "swatches",
            "baseName": "swatches",
            "type": "Array<EntitymanagerAttributeOptionSwatch>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerAttributeOption.attributeTypeMap;
    }

    public constructor() {
    }
}

