/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerAttribute } from '../models/EntitymanagerAttribute';
import { HttpFile } from '../http/http';

export class EntitymanagerEntity {
    'tenantId'?: string;
    'id'?: string;
    'type'?: string;
    'code'?: string;
    'parentCode'?: string;
    'label'?: string;
    'relationships'?: Array<string>;
    'attributes'?: Array<EntitymanagerAttribute>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentCode",
            "baseName": "parentCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<EntitymanagerAttribute>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerEntity.attributeTypeMap;
    }

    public constructor() {
    }
}

