/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerEntity } from '../models/EntitymanagerEntity';
import { HttpFile } from '../http/http';

export class EntitymanagerListEntitiesResponse {
    'entities'?: Array<EntitymanagerEntity>;
    'nextPage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entities",
            "baseName": "entities",
            "type": "Array<EntitymanagerEntity>",
            "format": ""
        },
        {
            "name": "nextPage",
            "baseName": "nextPage",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerListEntitiesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

