/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerOptionsList } from '../models/EntitymanagerOptionsList';
import { HttpFile } from '../http/http';

export class EntitymanagerUpdateOptionsListRequest {
    'tenantId'?: string;
    'optionList'?: EntitymanagerOptionsList;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "optionList",
            "baseName": "optionList",
            "type": "EntitymanagerOptionsList",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerUpdateOptionsListRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

