/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerRenderAs } from '../models/EntitymanagerRenderAs';
import { HttpFile } from '../http/http';

export class EntitymanagerUpdateAttributeRequestPayload {
    'label'?: string;
    '_default'?: string;
    'sort'?: number;
    'groupCode'?: string;
    'title'?: { [key: string]: string; };
    'renderAs'?: EntitymanagerRenderAs;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "string",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "groupCode",
            "baseName": "groupCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "renderAs",
            "baseName": "renderAs",
            "type": "EntitymanagerRenderAs",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerUpdateAttributeRequestPayload.attributeTypeMap;
    }

    public constructor() {
    }
}



