/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerAttributeGroup } from '../models/EntitymanagerAttributeGroup';
import { HttpFile } from '../http/http';

export class EntitymanagerListAttributeGroupsResponse {
    'attributeGroups'?: Array<EntitymanagerAttributeGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attributeGroups",
            "baseName": "attributeGroups",
            "type": "Array<EntitymanagerAttributeGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerListAttributeGroupsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

