/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerUpdateAttributeGroupRequestPayload } from '../models/EntitymanagerUpdateAttributeGroupRequestPayload';
import { HttpFile } from '../http/http';

export class EntitymanagerUpdateAttributeGroupRequest {
    'tenantId'?: string;
    'code'?: string;
    'payload'?: EntitymanagerUpdateAttributeGroupRequestPayload;
    'fieldMask'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "EntitymanagerUpdateAttributeGroupRequestPayload",
            "format": ""
        },
        {
            "name": "fieldMask",
            "baseName": "fieldMask",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerUpdateAttributeGroupRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

