/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerAttributeWriteErrors } from '../models/EntitymanagerAttributeWriteErrors';
import { EntitymanagerEntity } from '../models/EntitymanagerEntity';
import { HttpFile } from '../http/http';

export class EntitymanagerCreateEntityResponse {
    'attributeWriteErrors'?: EntitymanagerAttributeWriteErrors;
    'entity'?: EntitymanagerEntity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attributeWriteErrors",
            "baseName": "attributeWriteErrors",
            "type": "EntitymanagerAttributeWriteErrors",
            "format": ""
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "EntitymanagerEntity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerCreateEntityResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

