/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitymanagerAttribute } from '../models/EntitymanagerAttribute';
import { HttpFile } from '../http/http';

export class EntitymanagerBulkCreateAttributeResponse {
    'attributes'?: Array<EntitymanagerAttribute>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<EntitymanagerAttribute>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EntitymanagerBulkCreateAttributeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

