/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListProductsRequestFilter {
    'createdAtStart'?: Date;
    'createdAtEnd'?: Date;
    'updatedAtStart'?: Date;
    'updatedAtEnd'?: Date;
    'status'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAtStart",
            "baseName": "createdAtStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAtEnd",
            "baseName": "createdAtEnd",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAtStart",
            "baseName": "updatedAtStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAtEnd",
            "baseName": "updatedAtEnd",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListProductsRequestFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

