/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListProductsRequestFilter } from '../models/ListProductsRequestFilter';
import { HttpFile } from '../http/http';

export class ProductListProductsRequest {
    'tenantId'?: string;
    'pageSize'?: string;
    'pageToken'?: string;
    'filter'?: ListProductsRequestFilter;
    'filterMask'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ListProductsRequestFilter",
            "format": ""
        },
        {
            "name": "filterMask",
            "baseName": "filterMask",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductListProductsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

