/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductProductEntity } from '../models/ProductProductEntity';
import { HttpFile } from '../http/http';

export class ProductGetProductByUrlKeyResponse {
    'product'?: ProductProductEntity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "product",
            "baseName": "product",
            "type": "ProductProductEntity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductGetProductByUrlKeyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

