/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductAssetsEntry } from '../models/ProductAssetsEntry';
import { HttpFile } from '../http/http';

export class ProductBulkAddAssetsEntriesResponse {
    'assets'?: Array<ProductAssetsEntry>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<ProductAssetsEntry>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductBulkAddAssetsEntriesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

