/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductLocalizedText } from '../models/ProductLocalizedText';
import { HttpFile } from '../http/http';

export class ProductAssetsEntryMetadata {
    'roles'?: Array<string>;
    'alt'?: ProductLocalizedText;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "alt",
            "baseName": "alt",
            "type": "ProductLocalizedText",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAssetsEntryMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

