/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductLocalizedText } from '../models/ProductLocalizedText';
import { ProductProductVariant } from '../models/ProductProductVariant';
import { ProtobufAny } from '../models/ProtobufAny';
import { HttpFile } from '../http/http';

export class ProductCreateProductRequest {
    'tenantId'?: string;
    'entityType'?: string;
    'entityCode'?: string;
    'code'?: string;
    'isConfigurable'?: boolean;
    'variantAttributes'?: Array<string>;
    'isVirtual'?: boolean;
    'isGiftcard'?: boolean;
    'hasConfigurator'?: boolean;
    'urlKey'?: ProductLocalizedText;
    'maxSaleableQuantity'?: number;
    'mediaVariantAttributes'?: Array<string>;
    'attributes'?: { [key: string]: ProtobufAny; };
    'variants'?: { [key: string]: ProductProductVariant; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entityType",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityCode",
            "baseName": "entityCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "isConfigurable",
            "baseName": "isConfigurable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "variantAttributes",
            "baseName": "variantAttributes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "isVirtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isGiftcard",
            "baseName": "isGiftcard",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasConfigurator",
            "baseName": "hasConfigurator",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "urlKey",
            "baseName": "urlKey",
            "type": "ProductLocalizedText",
            "format": ""
        },
        {
            "name": "maxSaleableQuantity",
            "baseName": "maxSaleableQuantity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "mediaVariantAttributes",
            "baseName": "mediaVariantAttributes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: ProtobufAny; }",
            "format": ""
        },
        {
            "name": "variants",
            "baseName": "variants",
            "type": "{ [key: string]: ProductProductVariant; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCreateProductRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

