/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductAttributeResponseError } from '../models/ProductAttributeResponseError';
import { ProductProductResponseError } from '../models/ProductProductResponseError';
import { HttpFile } from '../http/http';

export class ProductCreateProductResponse {
    'success'?: boolean;
    'id'?: string;
    'productErrors'?: Array<ProductProductResponseError>;
    'attributeErrors'?: Array<ProductAttributeResponseError>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "productErrors",
            "baseName": "productErrors",
            "type": "Array<ProductProductResponseError>",
            "format": ""
        },
        {
            "name": "attributeErrors",
            "baseName": "attributeErrors",
            "type": "Array<ProductAttributeResponseError>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCreateProductResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

