/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductAttributeResponseError {
    'code'?: string;
    'message'?: string;
    'attributeCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributeCode",
            "baseName": "attributeCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAttributeResponseError.attributeTypeMap;
    }

    public constructor() {
    }
}

