/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductProductVariant } from '../models/ProductProductVariant';
import { HttpFile } from '../http/http';

export class ProductListVariantsBySkuResponse {
    'variants'?: Array<ProductProductVariant>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "variants",
            "baseName": "variants",
            "type": "Array<ProductProductVariant>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductListVariantsBySkuResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

