/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductBulkUpdateResponseResponse } from '../models/ProductBulkUpdateResponseResponse';
import { HttpFile } from '../http/http';

export class ProductBulkUpdateResponse {
    'productResponse'?: Array<ProductBulkUpdateResponseResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productResponse",
            "baseName": "productResponse",
            "type": "Array<ProductBulkUpdateResponseResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductBulkUpdateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

