/**
 * Product Service
 * API for managing products
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductBulkUpdateResponseV2Response } from '../models/ProductBulkUpdateResponseV2Response';
import { HttpFile } from '../http/http';

export class ProductBulkUpdateResponseV2 {
    'productResponse'?: Array<ProductBulkUpdateResponseV2Response>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productResponse",
            "baseName": "productResponse",
            "type": "Array<ProductBulkUpdateResponseV2Response>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductBulkUpdateResponseV2.attributeTypeMap;
    }

    public constructor() {
    }
}

